"""
dashboard/pages/score_applicant.py — Tab 1: Score an Applicant

Restructured into 3 sequential zones:
    Zone 1: Input Form with demo personas
    Zone 2: Score Result (gauge + decision + quick summary)
    Zone 3: Deep Dive (tabs: Why This Score? | Feature Impact | How to Improve | Download Report)

Includes AI chat panel at bottom (requires Gemini API key).
"""

import sys
import os
import time
import numpy as np
import pandas as pd
import streamlit as st

# Add project root to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from dashboard.components.gauge_chart import create_gigscore_gauge
from dashboard.components.shap_chart import create_shap_waterfall
from dashboard.components.metrics_card import (
    render_decision_badge, render_credit_limit,
)
from src.scoring.score_calculator import get_full_score_result, get_score_band
from src.features.gig_features import engineer_gig_features
from src.features.india_features import engineer_india_features
from src.explainability.reason_codes import get_reason_codes


# ─────────────────────────────────────────────────────────────────────
# Demo Personas
# ─────────────────────────────────────────────────────────────────────
PERSONAS = {
    'rahul': {
        'name': '🟢 Rahul — High-Performing Swiggy Driver',
        'monthly_earnings': 45000, 'income_volatility': 0.15,
        'income_gaps': 0, 'tenure': 36, 'rating': 4.7,
        'consistency': 0.92, 'cancel_rate': 0.03, 'upi_count': 85,
        'upi_consistency': 0.91, 'has_savings': True,
        'rent_ratio': 0.22, 'dependents': 1, 'years_city': 7.0,
    },
    'priya': {
        'name': '🟡 Priya — Part-Time Urban Company Pro',
        'monthly_earnings': 28000, 'income_volatility': 0.40,
        'income_gaps': 2, 'tenure': 14, 'rating': 4.1,
        'consistency': 0.65, 'cancel_rate': 0.08, 'upi_count': 35,
        'upi_consistency': 0.70, 'has_savings': True,
        'rent_ratio': 0.35, 'dependents': 2, 'years_city': 3.0,
    },
    'vikram': {
        'name': '🔴 Vikram — New Ola Driver, Irregular',
        'monthly_earnings': 18000, 'income_volatility': 0.65,
        'income_gaps': 4, 'tenure': 5, 'rating': 3.5,
        'consistency': 0.40, 'cancel_rate': 0.18, 'upi_count': 12,
        'upi_consistency': 0.45, 'has_savings': False,
        'rent_ratio': 0.50, 'dependents': 4, 'years_city': 1.0,
    },
}

DEFAULT_VALUES = {
    'monthly_earnings': 32000, 'income_volatility': 0.35,
    'income_gaps': 1, 'tenure': 24, 'rating': 4.3,
    'consistency': 0.78, 'cancel_rate': 0.06, 'upi_count': 38,
    'upi_consistency': 0.82, 'has_savings': True,
    'rent_ratio': 0.28, 'dependents': 2, 'years_city': 4.5,
}


def _get_defaults():
    key = st.session_state.get('selected_persona')
    if key and key in PERSONAS:
        return PERSONAS[key]
    return DEFAULT_VALUES


def _generate_report_markdown(ss):
    """Generate downloadable markdown report from session state."""
    pos = ss.get('positive_reasons', [])
    neg = ss.get('negative_reasons', [])
    tips = ss.get('improvement_tips', [])
    return f"""# GigScore Credit Report

**Score:** {ss['score']}/100 — {ss['band_label']}
**Decision:** {ss['decision']}
**Recommended Credit Limit:** ₹{ss['credit_limit']:,}
**Default Probability:** {ss['default_prob']:.4f}

## Positive Factors
{chr(10).join(f"- {r.get('reason', r)}" for r in pos) if pos else "- No significant positive factors identified"}

## Risk Factors
{chr(10).join(f"- {r.get('reason', r)}" for r in neg) if neg else "- No significant risk factors identified"}

## How to Improve Your Score
{chr(10).join(f"{i+1}. {t.get('tip', t)} ({t.get('impact', '')})" for i, t in enumerate(tips)) if tips else "- Maintain consistent platform activity and on-time payments"}

---
*Generated by GigScore — AI-powered alternative credit scoring for India's gig economy*
"""


def render_score_applicant_page():
    """Renders the Score an Applicant page."""

    st.markdown("""
    <h1 style="text-align: center; color: #f1f5f9; margin-bottom: 4px;">
        🎯 Score a Gig Worker Applicant
    </h1>
    <p style="text-align: center; color: #64748b; font-size: 14px; margin-bottom: 24px;">
        Enter the applicant's profile details to calculate their GigScore
    </p>
    """, unsafe_allow_html=True)

    # Initialize session state
    for key in ['score', 'default_prob', 'credit_limit', 'decision',
                'band_label', 'band_color', 'decision_detail',
                'positive_reasons', 'negative_reasons', 'improvement_tips',
                'waterfall_data', 'processing_ms']:
        if key not in st.session_state:
            st.session_state[key] = None

    # ═══════════════════════════════════════════════════════════════
    # ZONE 1 — Input Form
    # ═══════════════════════════════════════════════════════════════
    st.markdown("#### 👤 Quick Demo Personas")
    st.caption("Click a persona to auto-fill the form with realistic gig worker profiles")
    pcol1, pcol2, pcol3 = st.columns(3)
    with pcol1:
        if st.button("🟢 Rahul — Excellent", use_container_width=True, key="btn_rahul"):
            st.session_state['selected_persona'] = 'rahul'
            st.session_state['score'] = None  # Clear previous results
            st.rerun()
    with pcol2:
        if st.button("🟡 Priya — Average", use_container_width=True, key="btn_priya"):
            st.session_state['selected_persona'] = 'priya'
            st.session_state['score'] = None
            st.rerun()
    with pcol3:
        if st.button("🔴 Vikram — High Risk", use_container_width=True, key="btn_vikram"):
            st.session_state['selected_persona'] = 'vikram'
            st.session_state['score'] = None
            st.rerun()

    active = st.session_state.get('selected_persona')
    if active and active in PERSONAS:
        st.info(f"📋 Loaded: **{PERSONAS[active]['name']}**")

    st.markdown("---")
    defaults = _get_defaults()

    # Input form in 3 columns
    fc1, fc2, fc3 = st.columns(3)

    with fc1:
        st.markdown("**💰 Income & Earnings**")
        monthly_earnings = st.slider("Monthly Earnings (₹)", 8000, 150000,
                                     defaults['monthly_earnings'], 500,
                                     help="Average monthly gig income in INR")
        income_volatility = st.slider("Income Volatility", 0.0, 1.0,
                                      defaults['income_volatility'], 0.05,
                                      help="0 = very stable, 1 = very volatile")
        income_gaps = st.number_input("Income Gap Months (last year)", 0, 12,
                                      defaults['income_gaps'],
                                      help="Months with zero or very low earnings")

    with fc2:
        st.markdown("**📱 Platform Activity**")
        tenure = st.slider("Platform Tenure (months)", 1, 84, defaults['tenure'])
        rating = st.slider("Platform Rating", 1.0, 5.0, defaults['rating'], 0.1)
        consistency = st.slider("Weekly Work Consistency", 0.0, 1.0,
                                defaults['consistency'], 0.05,
                                help="Ratio of weeks with regular activity")
        cancel_rate = st.slider("Cancellation Rate", 0.0, 1.0,
                                defaults['cancel_rate'], 0.01)

    with fc3:
        st.markdown("**🏦 Digital & Financial**")
        upi_count = st.number_input("UPI Transactions/Month", 0, 300, defaults['upi_count'])
        upi_consistency = st.slider("UPI Consistency Score", 0.0, 1.0,
                                     defaults['upi_consistency'], 0.05)
        has_savings = st.checkbox("Has Savings Account", value=defaults['has_savings'])
        rent_ratio = st.slider("Rent-to-Income Ratio", 0.0, 0.8, defaults['rent_ratio'], 0.02)
        dependents = st.number_input("Dependents Count", 0, 8, defaults['dependents'])
        years_city = st.number_input("Years in City", 0.5, 30.0, defaults['years_city'], 0.5)

    # Calculate button
    calculate = st.button("🔮 Calculate GigScore", type="primary",
                          use_container_width=True,
                          disabled=st.session_state.get("running", False))

    # ═══════════════════════════════════════════════════════════════
    # SCORING LOGIC
    # ═══════════════════════════════════════════════════════════════
    if calculate:
        st.session_state["running"] = True
        with st.spinner("Calculating your GigScore..."):
            start_time = time.time()

            input_data = {
                'monthly_earnings_inr': monthly_earnings,
                'monthly_earnings_proxy': monthly_earnings,
                'income_volatility_coefficient': income_volatility,
                'income_gap_months_last_year': income_gaps,
                'income_trend_6m': 0.05,
                'platform_tenure_months': tenure,
                'platform_rating': rating,
                'active_platforms_count': 2,
                'weekly_work_consistency': consistency,
                'cancellation_rate': cancel_rate,
                'monthly_trips_or_orders': 180,
                'upi_transaction_count_monthly': upi_count,
                'upi_transaction_consistency_score': upi_consistency,
                'has_savings_account': int(has_savings),
                'rent_to_income_ratio': rent_ratio,
                'years_in_city': years_city,
                'dependents_count': dependents,
                'has_life_insurance': 0,
                'owns_smartphone_above_10k': 1,
                'vehicle_owned': 'two_wheeler',
                'mobile_recharge_frequency': 2,
                'late_night_work_ratio': 0.1,
                'digital_wallet_balance_avg': 2500,
                'income_log': np.log1p(monthly_earnings),
                'data_source': 'dashboard_input',
                'region_risk_rating': 2,
                'age': 30,
            }

            df = pd.DataFrame([input_data])
            df = engineer_gig_features(df)
            df = engineer_india_features(df)

            explanation = None
            try:
                import joblib
                artifacts_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'artifacts')
                model = joblib.load(os.path.join(artifacts_dir, 'ensemble_model.pkl'))
                pipeline = joblib.load(os.path.join(artifacts_dir, 'feature_pipeline.pkl'))
                metadata = {}
                meta_path = os.path.join(artifacts_dir, 'model_metadata.json')
                if os.path.exists(meta_path):
                    import json
                    with open(meta_path) as f:
                        metadata = json.load(f)

                feature_names = metadata.get('feature_names', [])
                for col in feature_names:
                    if col not in df.columns:
                        df[col] = np.nan

                X = pipeline.transform(df)
                default_prob = float(model.predict_proba(X)[:, 1][0])

                try:
                    explainer_path = os.path.join(artifacts_dir, 'shap_explainer.pkl')
                    if os.path.exists(explainer_path):
                        explainer = joblib.load(explainer_path)
                        explanation = explainer.explain_prediction(X[0])
                except Exception:
                    explanation = None

            except Exception:
                logit = (
                    -1.5 - 0.00002 * monthly_earnings
                    + 1.8 * income_volatility + 1.2 * income_gaps / 6
                    - 0.8 * tenure / 84 - 0.6 * rating / 5
                    - 0.4 * consistency + 0.7 * cancel_rate
                    - 0.3 * upi_consistency + 0.5 * rent_ratio
                    + 0.2 * dependents / 6 - 0.25 * int(has_savings)
                )
                logit += 1.5 * income_volatility * (income_gaps / 6)
                logit += 0.8 * float(tenure < 6)
                income_norm = (monthly_earnings - 8000) / (150000 - 8000)
                logit += 1.0 * (1 - income_norm) * income_volatility
                stability = (1 - income_volatility) * consistency
                logit -= 0.8 * stability ** 2
                logit += 0.6 * cancel_rate * (1 - rating / 5)
                logit -= 0.4 * int(has_savings) * (1 - rent_ratio)
                default_prob = 1 / (1 + np.exp(-logit))

            score_result = get_full_score_result(default_prob, monthly_earnings)
            score = score_result['gigscore']
            band_info = get_score_band(score)

            if explanation:
                reasons = get_reason_codes(explanation['feature_contributions'])
            else:
                positive = []
                negative = []
                if consistency > 0.7:
                    positive.append("Regular weekly work patterns show disciplined earning behavior")
                if rating > 4.0:
                    positive.append("High customer ratings reflect service quality and professionalism")
                if has_savings:
                    positive.append("Having a savings account indicates financial planning behavior")
                if monthly_earnings > 35000:
                    positive.append("Monthly earnings demonstrate strong earning capacity")
                if income_volatility > 0.4:
                    negative.append("Significant income volatility increases repayment uncertainty")
                if cancel_rate > 0.1:
                    negative.append("High cancellation rate signals potential reliability issues")
                if rent_ratio > 0.35:
                    negative.append("High rent burden relative to income leaves little room for repayment")
                if income_gaps > 2:
                    negative.append("Multiple income gap months suggest earning instability")
                if tenure < 12:
                    negative.append("Short platform history limits assessment of income reliability")
                reasons = {
                    'positive_reasons': [{'reason': r} for r in positive[:3]],
                    'negative_reasons': [{'reason': r} for r in negative[:3]],
                    'improvement_tips': [
                        {'tip': 'Maintain consistent weekly work schedules', 'impact': '+3 to +8 points'},
                        {'tip': 'Build longer platform tenure for better scoring', 'impact': '+2 to +6 points'},
                        {'tip': 'Use UPI consistently to build digital financial footprint', 'impact': '+3 to +7 points'},
                    ],
                }

            processing_ms = (time.time() - start_time) * 1000

            # Store everything in session state
            st.session_state.update({
                'score': score,
                'default_prob': default_prob,
                'credit_limit': score_result['credit_limit_recommendation'],
                'decision': score_result['loan_decision'],
                'decision_detail': score_result['decision_detail'],
                'band_label': band_info['label'],
                'band_color': band_info['color'],
                'positive_reasons': reasons.get('positive_reasons', []),
                'negative_reasons': reasons.get('negative_reasons', []),
                'improvement_tips': reasons.get('improvement_tips', []),
                'waterfall_data': explanation.get('waterfall_data') if explanation else None,
                'processing_ms': processing_ms,
                'running': False,
            })

    # ═══════════════════════════════════════════════════════════════
    # ZONE 2 — Score Result (only after calculation)
    # ═══════════════════════════════════════════════════════════════
    if st.session_state.get('score') is not None:
        st.markdown("---")
        st.markdown("## 🏦 Score Result")

        zc1, zc2, zc3 = st.columns([1.2, 1, 1.2])

        with zc1:
            fig = create_gigscore_gauge(
                st.session_state['score'],
                st.session_state['band_label'],
                st.session_state['band_color']
            )
            st.plotly_chart(fig, use_container_width=True, key="gauge_chart")

            # Score band legend
            st.markdown("""
            | Score | Category | Decision |
            |-------|----------|----------|
            | 0–39 | 🔴 Very Poor | Rejected |
            | 40–54 | 🟠 Poor | Conditional |
            | 55–69 | 🟡 Fair | Approved |
            | 70–84 | 🟢 Good | Approved |
            | 85–100 | 💎 Excellent | Max Limit |
            """)

        with zc2:
            render_decision_badge(
                st.session_state['decision'],
                st.session_state['decision_detail'],
            )
            render_credit_limit(st.session_state['credit_limit'])

            # Credit limit formula expander
            with st.expander("📋 How is the credit limit calculated?"):
                st.markdown("""
                | Score Range | Category | Max Credit Limit |
                |-------------|----------|-----------------|
                | 0 – 39 | Very Poor | ₹0 (Rejected) |
                | 40 – 54 | Poor | Up to ₹25,000 |
                | 55 – 69 | Fair | Up to ₹75,000 |
                | 70 – 84 | Good | Up to ₹1,50,000 |
                | 85 – 100 | Excellent | Up to ₹3,00,000 |

                Within each band, the limit scales with income:
                `credit_limit = min(income_multiple × monthly_income, band_cap)`

                Conditional approvals require a guarantor or collateral.
                """)

            st.caption(f"⚡ Processed in {st.session_state.get('processing_ms', 0):.0f}ms")

        with zc3:
            st.markdown("**Quick Summary**")
            pos = st.session_state.get('positive_reasons', [])
            neg = st.session_state.get('negative_reasons', [])
            if pos:
                st.success(f"✅ **Top Strength:** {pos[0].get('reason', str(pos[0]))}")
            if neg:
                st.error(f"❌ **Top Risk:** {neg[0].get('reason', str(neg[0]))}")

            st.metric("Default Probability", f"{st.session_state['default_prob']:.4f}")
            st.metric("GigScore", f"{st.session_state['score']}/100")

        # ═══════════════════════════════════════════════════════════
        # ZONE 3 — Deep Dive Tabs
        # ═══════════════════════════════════════════════════════════
        st.markdown("---")
        tab1, tab2, tab3, tab4 = st.tabs([
            "🔍 Why This Score?", "📊 Feature Impact",
            "💡 How to Improve", "📄 Download Report"
        ])

        with tab1:
            col_pos, col_neg = st.columns(2)
            with col_pos:
                st.markdown("### ✅ Positive Factors")
                for f in st.session_state.get('positive_reasons', []):
                    reason = f.get('reason', str(f))
                    impact = f.get('impact_strength', None)
                    with st.container():
                        st.markdown(f"**✓** {reason}")
                        if impact:
                            st.caption(f"Impact strength: {impact:.3f}")
                        st.divider()
                if not pos:
                    st.caption("No significant positive factors identified")

            with col_neg:
                st.markdown("### ❌ Risk Factors")
                for f in st.session_state.get('negative_reasons', []):
                    reason = f.get('reason', str(f))
                    impact = f.get('impact_strength', None)
                    with st.container():
                        st.markdown(f"**✗** {reason}")
                        if impact:
                            st.caption(f"Impact strength: {impact:.3f}")
                        st.divider()
                if not neg:
                    st.caption("No significant risk factors identified")

        with tab2:
            wd = st.session_state.get('waterfall_data')
            if wd:
                fig_shap = create_shap_waterfall(
                    wd['features'], wd['values'], wd.get('base_value', 0)
                )
                st.plotly_chart(fig_shap, use_container_width=True, key="shap_waterfall")
            else:
                st.info("SHAP feature impact chart is available when the trained model is used. "
                        "Currently using heuristic scoring.")

        with tab3:
            st.markdown("### 💡 How to Improve Your Score")
            tips = st.session_state.get('improvement_tips', [])
            for i, tip_data in enumerate(tips[:5], 1):
                if isinstance(tip_data, dict):
                    tip_text = tip_data.get('tip', str(tip_data))
                    impact = tip_data.get('impact', '')
                else:
                    tip_text = str(tip_data)
                    impact = ''

                with st.container():
                    cols = st.columns([1, 6, 2])
                    cols[0].markdown(f"**{i}.**")
                    cols[1].markdown(tip_text)
                    if impact:
                        cols[2].markdown(f"📈 **{impact}**")
                    st.divider()

        with tab4:
            report_md = _generate_report_markdown(st.session_state)
            st.download_button(
                "📄 Download Credit Report",
                data=report_md,
                file_name=f"gigscore_report_{st.session_state['score']}.md",
                mime="text/markdown",
                use_container_width=True,
            )
            with st.expander("Preview Report"):
                st.markdown(report_md)

        # ═══════════════════════════════════════════════════════════
        # AI ASSISTANT (Pollinations.ai — Free, no API key needed)
        # ═══════════════════════════════════════════════════════════
        st.markdown("---")

        ai_col1, ai_col2 = st.columns([3, 1])

        with ai_col1:
            st.markdown("### 🤖 Ask GigScore AI")
            st.caption("AI-powered score analysis — ask anything about this applicant's profile.")

        with ai_col2:
            # AI-generated score visualization with fallback
            try:
                from src.ai_assistant import get_ai_generated_image_url
                img_url = get_ai_generated_image_url(
                    st.session_state['score'],
                    st.session_state['band_label']
                )
                st.image(img_url, caption=f"{st.session_state['band_label']} Score Visual", width=150)
            except Exception:
                # Fallback: styled HTML badge instead of broken image
                _badge_colors = {
                    'EXCELLENT': ('#22c55e', '💎'), 'GOOD': ('#84cc16', '🟢'),
                    'FAIR': ('#f59e0b', '🟡'), 'POOR': ('#ef4444', '🟠'),
                    'VERY POOR': ('#7f1d1d', '🔴'),
                }
                _bc, _be = _badge_colors.get(st.session_state.get('band_label', 'FAIR'), ('#f59e0b', '🟡'))
                st.markdown(f"""
                <div style="text-align: center; padding: 20px; background: linear-gradient(135deg, {_bc}22, {_bc}44);
                            border: 2px solid {_bc}; border-radius: 12px; margin: 8px 0;">
                    <div style="font-size: 40px;">{_be}</div>
                    <div style="color: {_bc}; font-weight: 700; font-size: 14px; margin-top: 4px;">
                        {st.session_state.get('band_label', 'SCORE')}
                    </div>
                </div>
                """, unsafe_allow_html=True)

        from src.ai_assistant import ask_gigscore_ai, build_applicant_context, get_demo_response

        if "chat_history" not in st.session_state:
            st.session_state["chat_history"] = []

        def _safe_ai_response(question, context):
            """Call AI API with automatic demo fallback on any failure."""
            try:
                response = ask_gigscore_ai(question, context)
                # Check if response indicates an error
                if any(err in response.lower() for err in ['trouble connecting', 'timed out', 'could not connect', 'went wrong']):
                    return get_demo_response(question)
                return response
            except Exception:
                return get_demo_response(question)

        # Handle pending question from suggested button click
        if st.session_state.get("pending_ai_question"):
            pending_q = st.session_state.pop("pending_ai_question")
            context = build_applicant_context(st.session_state)
            response = _safe_ai_response(pending_q, context)
            st.session_state["chat_history"].append({"role": "user", "content": pending_q})
            st.session_state["chat_history"].append({"role": "assistant", "content": response})

        # Render chat history
        for message in st.session_state["chat_history"]:
            with st.chat_message(message["role"]):
                st.write(message["content"])

        # Handle new typed input
        if prompt := st.chat_input("Ask about this score..."):
            st.session_state["chat_history"].append({"role": "user", "content": prompt})
            with st.chat_message("user"):
                st.write(prompt)

            context = build_applicant_context(st.session_state)
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    response = _safe_ai_response(prompt, context)
                st.write(response)
            st.session_state["chat_history"].append({"role": "assistant", "content": response})

        # Show suggestion buttons if no chat history yet
        if not st.session_state.get("chat_history"):
            st.markdown("**Try asking:**")
            q_cols = st.columns(3)
            questions = [
                "Why is my score this value?",
                "What's the fastest way to improve?",
                "Is this a good score for a loan?"
            ]
            for i, q in enumerate(questions):
                if q_cols[i].button(q, key=f"suggestion_{i}"):
                    st.session_state["pending_ai_question"] = q
                    st.rerun()

        # Disclaimer
        st.caption(
            "⚠️ This score is indicative only and does not constitute an actual "
            "credit approval. GigScore is designed as an alternative assessment tool "
            "for education and demonstration purposes."
        )
